<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Update="BigO\README.md">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>Readme.cs</LastGenOutput>
    </None>
    <None Update="Recursion\README.md">
      <LastGenOutput>Readme.cs</LastGenOutput>
      <Generator>TextTemplatingFilePreprocessor</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="BigO\README.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>README.md</DependentUpon>
    </Compile>
    <Compile Update="Recursion\README.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>README.md</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
